//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListView
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BaseEntities : DbContext
    {

        private static BaseEntities _context;

        public BaseEntities()
            : base("name=BaseEntities")
        {
        }

        public static BaseEntities GetContext()
        {
            if (_context == null) _context = new BaseEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Агенты> Агенты { get; set; }
        public virtual DbSet<Накладные> Накладные { get; set; }
        public virtual DbSet<Поставка> Поставка { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<Реализация> Реализация { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
    }
}
