//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Агенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Агенты()
        {
            this.Поставка = new HashSet<Поставка>();
            this.Реализация = new HashSet<Реализация>();
        }
    
        public int ID_Агента { get; set; }
        public string Тип_агента { get; set; }
        public string Наименование_агента { get; set; }
        public string Электронная_почта_агента { get; set; }
        public string Телефон_агента { get; set; }
        public byte[] Логотип_агента { get; set; }
        public string Юридический_адрес { get; set; }
        public int Приоритет { get; set; }
        public string Директор { get; set; }
        public double ИНН { get; set; }
        public int КПП { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Поставка> Поставка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Реализация> Реализация { get; set; }
    }
}
