//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Накладные = new HashSet<Накладные>();
        }
    
        public int ID_Продукции { get; set; }
        public string Наименование_продукции { get; set; }
        public string Тип_продукции { get; set; }
        public int Артикул { get; set; }
        public int Количество_человек_для_производства { get; set; }
        public int Номер_цеха_производства { get; set; }
        public decimal Минимальная_цена_для_агента { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Накладные> Накладные { get; set; }
    }
}
