//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Реализация
    {
        public int ID_Реализации { get; set; }
        public Nullable<int> ID_Поставки { get; set; }
        public Nullable<int> ID_Агента { get; set; }
        public string Продукция { get; set; }
        public string Наименование_агента { get; set; }
        public System.DateTime Дата_реализации { get; set; }
        public string Количество_продукции { get; set; }
    
        public virtual Агенты Агенты { get; set; }
        public virtual Поставка Поставка { get; set; }
    }
}
