//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NameCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Поставка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Поставка()
        {
            this.Реализация = new HashSet<Реализация>();
        }
    
        public int ID_Поставки { get; set; }
        public Nullable<int> ID_Склада { get; set; }
        public Nullable<int> ID_Агента { get; set; }
        public Nullable<int> ID_Накладной { get; set; }
        public Nullable<System.DateTime> Дата_поставки { get; set; }
    
        public virtual Агенты Агенты { get; set; }
        public virtual Накладные Накладные { get; set; }
        public virtual Склад Склад { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Реализация> Реализация { get; set; }
    }
}
